name: todo_open
description: A new Flutter application.
version: 1.0.2+3oo

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 0.1.2

dev_dependencies:
  intl: 0.15.8
  flutter_slidable: 0.5.3
  image_picker: 0.6.0+16
  file_picker: 1.3.8
  google_sign_in: 4.0.4
  firebase_core: 0.4.0+8
  firebase_auth: 0.11.1+12
  cloud_firestore: 0.12.7+1
  firebase_storage: 3.0.6
  flutter_local_notifications: 0.7.1+3
  scheduled_notifications: 1.0.0
  location: 2.3.5
  font_awesome_flutter: 8.5.0
  flutter_facebook_login: 2.0.1
  shared_preferences: 0.5.3+4
  http: 0.12.0+2
  flutter_twitter_login: 1.1.0
  google_maps_flutter: 0.5.2
  simple_animations: 1.3.3

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icon/arrow.png
    - lib/assets/icon/notification.png
    - lib/assets/icon/help.png
    - lib/assets/icon/timeline.png
    - lib/assets/icon/signout.png
    - lib/assets/icon/info.png
    - lib/assets/icon/settings.png
    - lib/assets/icon/drawerIcon.png
    - lib/assets/icon/today.png
    - lib/assets/icon/completed.png
    - lib/assets/icon/date.png
    - lib/assets/icon/attach.png
    - lib/assets/icon/notify.png
    - lib/assets/icon/priority.png
    - lib/assets/icon/checked.png
    - lib/assets/icon/delete.png
    - lib/assets/icon/logo.png
    - lib/assets/icon/send.png
    - lib/assets/icon/blue.png
    - lib/assets/icon/orange.png
    - lib/assets/icon/green.png
    - lib/assets/icon/red.png
    - lib/assets/icon/purple.png
    - lib/assets/icon/graph.png
    - lib/assets/icon/home.png
    - lib/assets/icon/user.png
    - lib/assets/icon/marker.png
    - lib/assets/icon/spinner.gif
    - lib/assets/bg/image.png
    - lib/assets/bg/sidebar_bg.png
    - lib/assets/bg/bar.png
    - lib/assets/gif/load.gif
    - lib/assets/gif/spinner.gif

  fonts:
    - family: OpenSansSemiBold
      fonts:
        - asset: lib/assets/fonts/OpenSansSemiBold.ttf
          weight: 400
    - family: OpenSansRegular
      fonts:
        - asset: lib/assets/fonts/OpenSansRegular.ttf
          weight: 400
    - family: OpenSansItalic
      fonts:
        - asset: lib/assets/fonts/OpenSansItalic.ttf
          weight: 400
